### ISSUE TITLE
How to get the Asm( command after finishing AsmHook

### ISSUE THREAD

**Issue by ExpertCoder14** [jacobly0/asmhook#2] opened 2020-12-29 21:20 UTC
I have finished installing AsmHook, but I still need the `Asm(` command to run assembly programs. But I don't see `Asm(` in the catalog. Where do I find it?

**Comment by adriweb** [comment] 2020-12-29 21:22
You don't need it, that's the point. Just run `prgmYOURPRGM` and it'll run as-is.
BTW, this is the same behavior as with OS 5.3/5.4, where you didn't need to put `Asm(` before anymore.

**Comment by ExpertCoder14** [comment] 2020-12-29 21:29
@adriweb I think I asked about the wrong part. Here is what happened:

1. `prgmASMHOOK` throws `ERR:INVALID`.
2. I go to CaibriJr, open arTIfiCE, and press <kbd>ENTER</kbd> on ASMHOOK. Nothing happens, and I quit.
3. After doing step 2, `prgmASMHOOK` now runs successfully from the Home screen.
4. My other programs still throw `ERR:INVALID` even after running step 3.

**Comment by adriweb** [comment] 2020-12-29 21:34
You shouldn't do that step 3 though. But at least it showed that it did work. What if you do step 1,2,4 ?

**Comment by ExpertCoder14** [comment] 2020-12-29 21:38
No luck.

**Comment by jacobly0** [comment] 2020-12-29 21:52
AsmHook does not support unsquished assembly programs.  Duplicate of #1.

**Closed by jacobly0** 2020-12-29 21:52 UTC

**Comment by ExpertCoder14** [comment] 2020-12-29 22:19
How do I resolve this?

**Comment by jacobly0** [comment] 2020-12-29 22:39
@ExpertCoder14 Either write it in assembly and assemble it on a computer or use `AsmComp(` on an OS that supports it.

**Comment by ExpertCoder14** [comment] 2020-12-30 07:02
@jacobly0 I don't have an OS that supports `AsmComp(`. How would I convert from the hex coded TI-BASIC programs to an actual assembly file?
